#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Sainsburys\Commands\ConsoleCommand;

$application = new Application();
$application->add(new ConsoleCommand());
$application->run();